// Industry filter values accepted by the lead database (snapshot 2026-09-30).
// Neutral module/const names: this list ships to the browser (IcpCard).
export const LEAD_INDUSTRIES = [
  "IT Services and IT Consulting",
  "Hospitals and Health Care",
  "Financial Services",
  "Higher Education",
  "Retail",
  "Software Development",
  "Government Administration",
  "Construction",
  "Banking",
  "Business Consulting and Services",
  "Real Estate",
  "Telecommunications",
  "Insurance",
  "Motor Vehicle Manufacturing",
  "Education Administration Programs",
  "Oil and Gas",
  "Advertising Services",
  "Hospitality",
  "Non-profit Organizations",
  "Technology; Information and Internet",
  "Food and Beverage Services",
  "Pharmaceutical Manufacturing",
  "Manufacturing",
  "Transportation; Logistics; Supply Chain and Storage",
  "Restaurants",
  "Appliances; Electrical; and Electronics Manufacturing",
  "Primary and Secondary Education",
  "Utilities",
  "Wellness and Fitness Services",
  "Staffing and Recruiting",
  "Food and Beverage Manufacturing",
  "Industrial Machinery Manufacturing",
  "Airlines and Aviation",
  "Machinery Manufacturing",
  "Mining",
  "Law Practice",
  "Chemical Manufacturing",
  "Research Services",
  "Retail Apparel and Fashion",
  "Environmental Services",
  "Wholesale",
  "Accounting",
  "Civil Engineering",
  "Defense and Space Manufacturing",
  "Truck Transportation",
  "Medical Equipment Manufacturing",
  "Entertainment Providers",
  "Medical Practices",
  "Facilities Services",
  "Outsourcing and Offshoring Consulting",
  "Consumer Services",
  "Biotechnology Research",
  "Human Resources Services",
  "Travel Arrangements",
  "Armed Forces",
  "Wholesale Building Materials",
  "Individual and Family Services",
  "Civic and Social Organizations",
  "Education",
  "Professional Training and Coaching",
  "Architecture and Planning",
  "Professional Services",
  "Spectator Sports",
  "Security and Investigations",
  "Legal Services",
  "Automation Machinery Manufacturing",
  "Broadcast Media Production and Distribution",
  "Aviation and Aerospace Component Manufacturing",
  "Farming",
  "Engineering Services",
  "Mental Health Care",
  "Design Services",
  "Personal Care Product Manufacturing",
  "Semiconductor Manufacturing",
  "Events Services",
  "Media Production",
  "Textile Manufacturing",
  "Marketing Services",
  "E-Learning Providers",
  "Computers and Electronics Manufacturing",
  "Information Services",
  "Investment Management",
  "International Trade and Development",
  "Packaging and Containers Manufacturing",
  "Book and Periodical Publishing",
  "Law Enforcement",
  "Plastics Manufacturing",
  "Maritime Transportation",
  "Computer and Network Security",
  "Retail Luxury Goods and Jewelry",
  "Retail Groceries",
  "Furniture and Home Furnishings Manufacturing",
  "Printing Services",
  "Religious Institutions",
  "Renewable Energy Semiconductor Manufacturing",
  "Public Relations and Communications Services",
  "Venture Capital and Private Equity Principals",
  "Public Safety",
  "Freight and Package Transportation",
  "Rail Transportation",
  "Computer Games",
  "Computer Hardware Manufacturing",
  "International Affairs",
  "Newspaper Publishing",
  "Retail Office Equipment",
  "Paper and Forest Product Manufacturing",
  "Executive Offices",
  "Technology; Information and Media",
  "Beverage Manufacturing",
  "Musicians",
  "Wholesale Import and Export",
  "Government Relations Services",
  "Motor Vehicle Parts Manufacturing",
  "Gambling Facilities and Casinos",
  "Market Research",
  "Performing Arts",
  "Administration of Justice",
  "Renewable Energy Power Generation",
  "Museums; Historical Sites; and Zoos",
  "Online Audio and Video Media",
  "Health and Human Services",
  "Services for Renewable Energy",
  "Sporting Goods Manufacturing",
  "Photography",
  "Veterinary Services",
  "Recreational Facilities",
  "Investment Banking",
  "Graphic Design",
  "Internet Publishing",
  "Movies; Videos; and Sound",
  "Public Policy Offices",
  "Retail Motor Vehicles",
  "Glass; Ceramics and Concrete Manufacturing",
  "Internet Marketplace Platforms",
  "Electric Power Generation",
  "Translation and Localization",
  "Shipbuilding",
  "Capital Markets",
  "Political Organizations",
  "Retail Pharmacies",
  "Leasing Non-residential Real Estate",
  "Retail Art Supplies",
  "Holding Companies",
  "Philanthropic Fundraising Services",
  "Urban Transit Services",
  "Retail Health and Personal Care Products",
  "Think Tanks",
  "Writing and Editing",
  "Artists and Writers",
  "Libraries",
  "Computer Networking Products",
  "IT System Custom Software Development",
  "Public Health",
  "Strategic Management Services",
  "Animation and Post-production",
  "Warehousing and Storage",
  "Railroad Equipment Manufacturing",
  "Medical and Diagnostic Laboratories",
  "Renewable Energy Equipment Manufacturing",
  "Alternative Medicine",
  "Ground Passenger Transportation",
  "Dairy Product Manufacturing",
  "Electric Power Transmission; Control; and Distribution",
  "Home Health Care Services",
  "Wireless Services",
  "Tobacco Manufacturing",
  "Energy Technology",
  "Paint; Coating; and Adhesive Manufacturing",
  "Fundraising",
  "Sports Teams and Clubs",
  "Solar Electric Power Generation",
  "Vehicle Repair and Maintenance",
  "Transportation Equipment Manufacturing",
  "Food and Beverage Retail",
  "Fabricated Metal Products",
  "Interior Design",
  "Data Infrastructure and Analytics",
  "Technical and Vocational Training",
  "Building Construction",
  "Electrical Equipment Manufacturing",
  "Agriculture; Construction; Mining Machinery Manufacturing",
  "Legislative Offices",
  "Social Networking Platforms",
  "Security Systems Services",
  "Fisheries",
  "Primary Metal Manufacturing",
  "Real Estate Agents and Brokers",
  "Apparel Manufacturing",
  "Commercial and Industrial Machinery Maintenance",
  "HVAC and Refrigeration Equipment Manufacturing",
  "Media and Telecommunications",
  "Wholesale Motor Vehicles and Parts",
  "Commercial Real Estate",
  "Insurance Agencies and Brokerages",
  "Community Services",
  "Mobile Gaming Apps",
  "Wholesale Food and Beverage",
  "Repair and Maintenance",
  "Sports and Recreation Instruction",
  "Blockchain Services",
  "Agricultural Chemical Manufacturing",
  "Blogs",
  "Industry Associations",
  "Space Research and Technology",
  "Ranching",
  "Oil; Gas; and Mining",
  "Nanotechnology Research",
  "IT System Data Services",
  "Retail Furniture and Home Furnishings",
  "Physical; Occupational and Speech Therapists",
  "Arts and Crafts",
  "Specialty Trade Contractors",
  "Online and Mail Order Retail",
  "Measuring and Control Instrument Manufacturing",
  "Internet News",
  "Hotels and Motels",
  "Fire Protection",
  "Program Development",
  "Nuclear Electric Power Generation",
  "Business Content",
  "Dentists",
  "Child Day Care Services",
  "Nursing Homes and Residential Care Facilities",
  "Personal Care Services",
  "Book Publishing",
  "Security Guards and Patrol Services",
  "Business Intelligence Platforms",
  "Equipment Rental Services",
  "Professional Organizations",
  "Operations Consulting",
  "Landscaping Services",
  "Movies and Sound Recording",
  "Office Furniture and Fixtures Manufacturing",
  "Climate Technology Product Manufacturing",
  "Wood Product Manufacturing",
  "Alternative Dispute Resolution",
  "Retail Appliances; Electrical; and Electronic Equipment",
  "Embedded Software Products",
  "Language Schools",
  "Commercial and Industrial Equipment Rental",
  "Retail Gasoline",
  "Farming; Ranching; Forestry",
  "Metal Treatments",
  "Robotics Engineering",
  "Data Security Software Products",
  "Glass Product Manufacturing",
  "Animal Feed Manufacturing",
  "Telephone Call Centers",
  "Residential Building Construction",
  "Housing and Community Development",
  "Administrative and Support Services",
  "Electric Lighting Equipment Manufacturing",
  "Wholesale Chemical and Allied Products",
  "Mobile Computing Software Products",
  "Pet Services",
  "Wholesale Appliances; Electrical; and Electronics",
  "Museums",
  "Hospitals",
  "Courts of Law",
  "Footwear Manufacturing",
  "Radio and Television Broadcasting",
  "Golf Courses and Country Clubs",
  "Community Development and Urban Planning",
  "Wholesale Drugs and Sundries",
  "School and Employee Bus Services",
  "Wholesale Metals and Minerals",
  "Waste Treatment and Disposal",
  "Wineries",
  "Janitorial Services",
  "Highway; Street; and Bridge Construction",
  "Commercial and Service Industry Machinery Manufacturing",
  "Wholesale Machinery",
  "Leasing Residential Real Estate",
  "Plastics and Rubber Product Manufacturing",
  "Architectural and Structural Metal Manufacturing",
  "Water Supply and Irrigation Systems",
  "Transportation Programs",
  "Executive Search Services",
  "Horticulture",
  "Wind Electric Power Generation",
  "Wholesale Petroleum and Petroleum Products",
  "Services for the Elderly and Disabled",
  "Military and International Affairs",
  "Fashion Accessories Manufacturing",
  "Wholesale Alcoholic Beverages",
  "IT System Design Services",
  "Utility System Construction",
  "Waste Collection",
  "Retail Building Materials and Garden Equipment",
  "Engines and Power Transmission Equipment Manufacturing",
  "Surveying and Mapping Services",
  "Real Estate and Equipment Rental Services",
  "Metalworking Machinery Manufacturing",
  "Investment Advice",
  "Accommodation and Food Services",
  "Digital Accessibility Services",
  "Conservation Programs",
  "Building Equipment Contractors",
  "Utilities Administration",
  "Wholesale Luxury Goods and Jewelry",
  "Metal Ore Mining",
  "Caterers",
  "Construction Hardware Manufacturing",
  "Wholesale Hardware; Plumbing; Heating Equipment",
  "Building Structure and Exterior Contractors",
  "Chemical Raw Materials Manufacturing",
  "IT System Training and Support",
  "Temporary Help Services",
  "Retail Art Dealers",
  "Desktop Computing Software Products",
  "Periodical Publishing",
  "Retail Office Supplies and Gifts",
  "Forestry and Logging",
  "Building Finishing Contractors",
  "Economic Programs",
  "Rubber Products Manufacturing",
  "Baked Goods Manufacturing",
  "Meat Products Manufacturing",
  "Water; Waste; Steam; and Air Conditioning Services",
  "Physicians",
  "Insurance and Employee Benefit Funds",
  "Amusement Parks and Arcades",
  "IT System Operations and Maintenance",
  "Leather Product Manufacturing",
  "Communications Equipment Manufacturing",
  "Electronic and Precision Equipment Maintenance",
  "Air; Water; and Waste Program Management",
  "Turned Products and Fastener Manufacturing",
  "Coal Mining",
  "Climate Data and Analytics",
  "Shuttles and Special Needs Transportation Services",
  "Taxi and Limousine Services",
  "Audio and Video Equipment Manufacturing",
  "Natural Gas Distribution",
  "Fine Arts Schools",
  "Emergency and Relief Services",
  "Household Appliance Manufacturing",
  "Wholesale Recyclable Materials",
  "Office Administration",
  "Wholesale Furniture and Home Furnishings",
  "Accessible Architecture and Design",
  "Insurance Carriers",
  "Sightseeing Transportation",
  "Telecommunications Carriers",
  "Ambulance Services",
  "Zoos and Botanical Gardens",
  "Wholesale Computer Equipment",
  "Mobile Food Services",
  "Satellite Telecommunications",
  "Vocational Rehabilitation Services",
  "Laundry and Drycleaning Services",
  "Funds and Trusts",
  "Nonresidential Building Construction",
  "Sugar and Confectionery Product Manufacturing",
  "Soap and Cleaning Product Manufacturing",
  "Breweries",
  "Bars; Taverns; and Nightclubs",
  "Hydroelectric Power Generation",
  "Optometrists",
  "IT System Testing and Evaluation",
  "Wholesale Apparel and Sewing Supplies",
  "Loan Brokers",
  "Wholesale Raw Farm Products",
  "Theater Companies",
  "Robot Manufacturing",
  "Performing Arts and Spectator Sports",
  "Collection Agencies",
  "Outpatient Care Centers",
  "Housing Programs",
  "Postal Services",
  "Household Services",
  "Fossil Fuel Electric Power Generation",
  "Seafood Product Manufacturing",
  "Consumer Goods Rental",
  "Wholesale Paper Products",
  "Retail Books and Printed News",
  "Fuel Cell Manufacturing",
  "Sound Recording",
  "Retail Florists",
  "Environmental Quality Programs",
  "Skiing Facilities",
  "Household and Institutional Furniture Manufacturing",
  "Trusts and Estates",
  "Retail Recyclable Materials and Used Merchandise",
  "Interurban and Rural Bus Services",
  "Retail Musical Instruments",
  "Claims Adjusting; Actuarial Services",
  "Chiropractors",
  "Public Assistance Programs",
  "Cosmetology and Barber Schools",
  "Biomass Electric Power Generation",
  "Steam and Air-Conditioning Supply",
  "Boilers; Tanks; and Shipping Container Manufacturing",
  "Dance Companies",
  "Flight Training",
  "Mattress and Blinds Manufacturing",
  "Distilleries",
  "Spring and Wire Product Manufacturing",
  "Pension Funds",
  "Bed-and-Breakfasts; Hostels; Homestays",
  "Securities and Commodity Exchanges",
  "Geothermal Electric Power Generation",
  "Pipeline Transportation",
  "Clay and Refractory Products Manufacturing",
  "Wholesale Footwear",
  "Historical Sites",
  "Savings Institutions",
  "Abrasives and Nonmetallic Minerals Manufacturing",
  "Correctional Institutions",
  "Personal and Laundry Services",
  "Oil and Coal Product Manufacturing",
  "Credit Intermediation",
  "Natural Gas Extraction",
  "Oil Extraction",
  "Nonmetallic Mineral Mining",
  "Metal Valve; Ball; and Roller Manufacturing",
  "Smart Meter Manufacturing",
  "Alternative Fuel Vehicle Manufacturing",
  "Fruit and Vegetable Preserves Manufacturing",
  "Funeral Services",
  "Accessible Hardware Manufacturing",
  "IT System Installation and Disposal",
  "Regenerative Design",
  "Cable and Satellite Programming",
  "Ranching and Fisheries",
  "Sheet Music Publishing",
  "Subdivision of Land",
  "Death Care Services",
  "Wholesale Photography Equipment and Supplies",
  "Reupholstery and Furniture Repair",
  "Cutlery and Handtool Manufacturing",
  "Racetracks",
  "Women's Handbag Manufacturing",
  "Lime and Gypsum Products Manufacturing",
  "Magnetic and Optical Media Manufacturing",
  "Artificial Rubber and Synthetic Fiber Manufacturing",
  "Footwear and Leather Goods Repair",
  "Family Planning Centers",
  "Secretarial Schools",
  "Circuses and Magic Shows",
  "Other"
] as const

export type LeadIndustry = (typeof LEAD_INDUSTRIES)[number]
